### ISSUE TITLE
The bash command crashes the shell

### ISSUE THREAD

**Issue by oOosys** [geophile/marcel#25]
```marcel
/home/o $ bash
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/o/.local/lib/python3.10/site-packages/marcel/main.py", line 314, in <module>
    main()
  File "/home/o/.local/lib/python3.10/site-packages/marcel/main.py", line 297, in main
    MAIN.run(print_prompt)
  File "/home/o/.local/lib/python3.10/site-packages/marcel/main.py", line 131, in run
    self.run_command(self.input)
  File "/home/o/.local/lib/python3.10/site-packages/marcel/main.py", line 143, in run_command
    pipeline = parser.parse()
  File "/home/o/.local/lib/python3.10/site-packages/marcel/parser.py", line 948, in parse
    return self.command()
  File "/home/o/.local/lib/python3.10/site-packages/marcel/parser.py", line 954, in command
    command = self.pipeline()
  File "/home/o/.local/lib/python3.10/site-packages/marcel/parser.py", line 1034, in pipeline
    pipeline.append(self.create_op(*op_args))
  File "/home/o/.local/lib/python3.10/site-packages/marcel/parser.py", line 1149, in create_op
    op = self.create_op_builtin(op_token, arg_tokens)
  File "/home/o/.local/lib/python3.10/site-packages/marcel/parser.py", line 1182, in create_op_builtin
    op_module.args_parser().parse(args, op)
  File "/home/o/.local/lib/python3.10/site-packages/marcel/op/bash.py", line 62, in parse
    if args[0] in ('-i', '--interactive'):
IndexError: list index out of range
~ $ 
```
Now after the IndexError the shell is back to bash. How to exit the marcel shell gracefully? `exit` or `quit` do not work ...

**Comment by geophile** [comment]
Fixed in 0.18.6.
